### ISSUE TITLE
require is not defined when used with ESM via ViteJS

### ISSUE THREAD

**Issue by stolinski** [lquixada/cross-fetch#108]
Importing in an esm setup on the server seems to break.

```
Error when evaluating SSR module /node_modules/cross-fetch/dist/node-ponyfill.js:
ReferenceError: require is not defined
    at /node_modules/cross-fetch/dist/node-ponyfill.js:1:17
```

Not sure if this is related to #46

**Comment by benwoodward** [comment]
I'm also having this issue using https://github.com/dgraph-io/dgraph-js-http/ and SvelteKit + `adapter-node`

```javascript
❯ node ./build
file:///Users/ben/dev/my-project/build/index.js:28
  throw new Error('Dynamic require of "' + x2 + '" is not supported');
        ^

Error: Dynamic require of "stream" is not supported
    at __require (file:///Users/ben/dev/my-project/build/index.js:28:9)
    at node_modules/node-fetch/lib/index.js (file:///Users/ben/dev/my-project/build/index.js:91:35)
    at __require2 (file:///Users/ben/dev/my-project/build/index.js:43:44)
    at node_modules/isomorphic-fetch/fetch-npm-node.js (file:///Users/ben/dev/my-project/build/index.js:1132:21)
    at __require2 (file:///Users/ben/dev/my-project/build/index.js:43:44)
    at node_modules/dgraph-js-http/lib/clientStub.js (file:///Users/ben/dev/my-project/build/index.js:4152:18)
    at __require2 (file:///Users/ben/dev/my-project/build/index.js:43:44)
    at node_modules/dgraph-js-http/lib/index.js (file:///Users/ben/dev/my-project/build/index.js:5142:19)
    at __require2 (file:///Users/ben/dev/my-project/build/index.js:43:44)
    at file:///Users/ben/dev/my-project/build/index.js:73298:25
```
`esbuild`:

```javascript
var __require = (x2) => {
  if (typeof require !== "undefined")
    return require(x2);
  throw new Error('Dynamic require of "' + x2 + '" is not supported');
};
```

https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#01123

I think this is relevant: https://github.com/vitejs/vite/issues/162

**Comment by eMeRiKa13** [comment]
Did you fix that @stolinski and @benwoodward? I have the same error with Nuxt3.

**Comment by benwoodward** [comment]
@eMeRiKa13 In my case this was a bug with SvelteKit's Node adapter iirc. I since switched to another adapter.
